# Generated by Django 5.1.4 on 2024-12-16 10:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('theShield', '0002_delete_files'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('username', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True)),
                ('email', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=30)),
                ('private_key', models.TextField(editable=False, unique=True)),
                ('public_key_key', models.TextField(editable=False, unique=True)),
                ('created', models.DateTimeField(default=datetime.datetime.now, editable=False)),
            ],
            options={
                'verbose_name': 'User',
            },
        ),
    ]
