# Generated by Django 5.1.4 on 2024-12-16 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theShield', '0003_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='public_key_key',
            new_name='public_key',
        ),
    ]
