# Generated by Django 5.1.4 on 2024-12-16 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theShield', '0004_rename_public_key_key_users_public_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='private_key',
            field=models.TextField(default='h', editable=False),
        ),
        migrations.AlterField(
            model_name='users',
            name='public_key',
            field=models.TextField(default='h', editable=False),
        ),
    ]
