# Generated by Django 5.1.4 on 2024-12-17 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theShield', '0009_alter_users_created_messages_delete_message'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Messages',
            new_name='Attachments',
        ),
    ]
