# Generated by Django 5.1.4 on 2024-12-17 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theShield', '0010_rename_messages_attachments'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Attachments',
            new_name='Messages',
        ),
    ]
