# Generated by Django 5.1.4 on 2024-12-17 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theShield', '0011_rename_attachments_messages'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Messages',
            new_name='Message',
        ),
    ]
