# Generated by Django 5.1.4 on 2024-12-17 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theShield', '0013_rename_message_messages'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messages',
            options={'verbose_name': 'Message'},
        ),
    ]
