# Generated by Django 5.1.4 on 2024-12-17 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theShield', '0014_alter_messages_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='key',
            field=models.TextField(blank=True, null=True),
        ),
    ]
