# Generated by Django 5.1.4 on 2024-12-21 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theShield', '0016_messages_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
