# Generated by Django 5.1.4 on 2024-12-21 14:26

import theShield.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theShield', '0018_remove_messages_id_messages_message_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to=theShield.models.dynamic_file_path),
        ),
    ]
