# Generated by Django 5.1.4 on 2024-12-30 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theShield', '0019_alter_messages_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='key',
            field=models.BinaryField(default=None, max_length=256),
        ),
    ]
