# Generated by Django 5.1.4 on 2024-12-30 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theShield', '0020_alter_messages_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='content',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
