# Generated by Django 5.1.4 on 2024-12-30 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theShield', '0021_alter_messages_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messages',
            old_name='content',
            new_name='ciphertext',
        ),
        migrations.AddField(
            model_name='messages',
            name='nonce',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='messages',
            name='tag',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
